"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](surface1)\
$os\
$username\
[](bg:teal fg:surface1)\
$directory\
[](fg:teal bg:green)\
$git_branch\
$git_status\
[](fg:green bg:teal)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:teal bg:mauve)\
$docker_context\
$time\
[ ](fg:mauve)\
$line_break$character"""

palette = 'kanagawa'

[palettes.kanagawa]
rosewater = "#D27E99"
flamingo = "#FF5D62"
pink = "#D27E99"
mauve = "#957FB8"
purple = "#957FB8"
red = "#E82424"
maroon = "#C34043"
orange = "#FFA066"
peach = "#FFA066"
yellow = "#E6C384"
green = "#98BB6C"
teal = "#7AA89F"
sky = "#7FB4CA"
sapphire = "#658594"
blue = "#7E9CD8"
lavender = "#9CABCA"
text = "#DCD7BA"
subtext1 = "#C8C093"
subtext0 = "#727169"
overlay2 = "#54546D"
overlay1 = "#717C7C"
overlay0 = "#43436C"
surface2 = "#363646"
surface1 = "#2A2A37"
surface0 = "#2A2A37"
base = "#1F1F28"
mantle = "#1C1C26"
crust = "#16161D"

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[palettes.tokyonight]
rosewater = "#f7768e"
flamingo = "#ff9e64"
pink = "#bb9af7"
orange = "#ff9e64"
red = "#f7768e"
maroon = "#db4b4b"
peach = "#ff9e64"
yellow = "#e0af68"
green = "#9ece6a"
teal = "#73daca"
sky = "#7dcfff"
sapphire = "#2ac3de"
blue = "#7aa2f7"
lavender = "#89ddff"
text = "#c0caf5"
subtext1 = "#a9b1d6"
subtext0 = "#737aa2"
overlay2 = "#545c7e"
overlay1 = "#737aa2"
overlay0 = "#565f89"
surface2 = "#414868"
surface1 = "#292e42"
surface0 = "#1e2030"
base = "#1a1b26"
mantle = "#16161e"
crust = "#15161e"
purple = "#bb9af7"

[os]
disabled = false
style = "bg:surface1 fg:text"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:surface1 fg:text"
style_root = "bg:surface1 fg:text"
format = '[ $user ]($style)'

[directory]
style = "fg:base bg:teal"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:teal"
format = '[[ $symbol $branch ](fg:base bg:green)]($style)'

[git_status]
style = "bg:teal"
format = '[[($all_status$ahead_behind )](fg:base bg:green)]($style)'

[nodejs]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[c]
symbol = " "
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[rust]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[golang]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[php]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[java]
symbol = " "
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[kotlin]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[haskell]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[python]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[docker_context]
symbol = ""
style = "bg:mauve"
format = '[[ $symbol( $context) ](fg:base bg:mauve)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:mauve"
format = '[[  $time ](fg:base bg:mauve)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:teal)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:blue)'
vimcmd_replace_one_symbol = '[](bold fg:mauve)'
vimcmd_replace_symbol = '[](bold fg:mauve)'
vimcmd_visual_symbol = '[](bold fg:sapphire)'
