$rosewater = rgb(d27e99)
$rosewaterAlpha = d27e99

$flamingo = rgb(ff5d62)
$flamingoAlpha = ff5d62

$pink = rgb(d27e99)
$pinkAlpha = d27e99

$mauve = rgb(957fb8)
$mauveAlpha = 957fb8

$red = rgb(e82424)
$redAlpha = e82424

$maroon = rgb(c34043)
$maroonAlpha = c34043

$peach = rgb(ffa066)
$peachAlpha = ffa066

$yellow = rgb(e6c384)
$yellowAlpha = e6c384

$green = rgb(98bb6c)
$greenAlpha = 98bb6c

$teal = rgb(7aa89f)
$tealAlpha = 7aa89f

$sky = rgb(7fb4ca)
$skyAlpha = 7fb4ca

$sapphire = rgb(658594)
$sapphireAlpha = 658594

$blue = rgb(7e9cd8)
$blueAlpha = 7e9cd8

$lavender = rgb(9cabca)
$lavenderAlpha = 9cabca

$text = rgb(dcd7ba)
$textAlpha = dcd7ba

$subtext1 = rgb(c8c093)
$subtext1Alpha = c8c093

$subtext0 = rgb(727169)
$subtext0Alpha = 727169

$overlay2 = rgb(54546d)
$overlay2Alpha = 54546d

$overlay1 = rgb(717c7c)
$overlay1Alpha = 717c7c

$overlay0 = rgb(43436c)
$overlay0Alpha = 43436c

$surface2 = rgb(363646)
$surface2Alpha = 363646

$surface1 = rgb(2a2a37)
$surface1Alpha = 2a2a37

$surface0 = rgb(1f1f28)
$surface0Alpha = 1f1f28

$base = rgb(1f1f28)
$baseAlpha = 1f1f28

$mantle = rgb(1c1c26)
$mantleAlpha = 1c1c26

$crust = rgb(16161d)
$crustAlpha = 16161d
